
# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf


################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
# monitor=HDMI-A-1,2560x1440@240,0x0,1
# monitor=eDP-1,2560x1600@240,2560x0,1.6

source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/programs.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/env.conf
source = ~/.config/hypr/modules/decorations.conf
source = ~/.config/hypr/modules/animations.conf
source = ~/.config/hypr/modules/windowrules.conf
source = ~/.config/hypr/modules/layouts.conf
source = ~/.config/hypr/modules/misc.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/binds.conf


# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more


#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input

###################
### KEYBINDINGS ###
###################

